backend:
  name: git-gateway
  branch: feature/venue
media_folder: content/images
public_folder: /assets
collections:
  - name: homepage
    label: Homepage
    files:
      - label: Homepage
        name: homepage
        file: content/homepage/homepage.json
        fields:
          - label: Introduction
            name: introduction
            widget: object
            fields:
              - {label: Description, name: description, widget: markdown}
              - {label: Newsletter title, name: newsletterTitle, widget: string}
              - {label: Newsletter button text, name: newsletterButton, widget: string}
          - label: Upcoming
            name: upcoming
            widget: object
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Description, name: description, widget: markdown}
            - {label: Video Id, name: videoId, widget: string}
            - label: Links
              name: links
              widget: list
              fields:
                - {label: Name, name: name, widget: string}
                - {label: Url, name: url, widget: string}
                - {label: New window, name: newWindow, widget: boolean}
          - label: Tiles
            name: tiles
            widget: object
            fields:
            - label: Tile One
              name: tileOne
              widget: object
              fields:
                - {label: Title, name: title, widget: string}
                - {label: Name, name: name, widget: string}
            - label: Tile Two
              name: tileTwo
              widget: object
              fields:
                - {label: Title, name: title, widget: string}
                - label: Names
                  name: names
                  widget: list
                  fields:
                    - {label: Name, name: name, widget: string}
            - label: Tile Three
              name: tileThree
              widget: object
              fields:
                - {label: Title, name: title, widget: string}
                - {label: Name, name: name, widget: string}
          - label: Map
            name: map
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
          - label: Venue
            name: venue
            widget: object
            fields:
              - {label: Description, name: description, widget: markdown}
          - label: Activities
            name: activities
            widget: object
            fields: 
              - {label: Title, name: title, widget: string}
              - label: Activity
                name: activity
                widget: list
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Date, name: date, widget: string}
                  - {label: Description, name: description, widget: markdown}
  - name: globals
    label: Globals
    files:
      - label: Globals
        name: globals
        file: content/globals.json
        fields:
          - label: Address
            name: address
            widget: object
            fields:
              - {label: Name, name: name, widget: string}
              - label: Coordinates
                name: coordinates
                widget: object
                fields:
                  - {label: Lat, name: lat, widget: string}
                  - {label: Long, name: lng, widget: string}
          - label: Header
            name: header
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subTitle, widget: string}
          - label: Footer
            name: footer
            widget: object
            fields:
              - label: Contact
                name: contact
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - label: Facebook
                    name: facebook
                    widget: object
                    fields:
                      - {label: Title, name: title, widget: string}
                      - {label: Url, name: url, widget: string}
                  - label: E-mail
                    name: email
                    widget: object
                    fields:
                      - {label: Title, name: title, widget: string}
                      - {label: Url, name: url, widget: string}
              - label: FAQ
                name: faq
                widget: object
                fields:
                  - label: Items
                    name: items
                    widget: list
                    fields:
                      - {label: Question, name: question, widget: string}
                      - {label: Answer, name: answer, widget: markdown}
              - {label: Copyright name, name: copyrightName, widget: string}
                  
                
    

