backend:
  name: git-gateway
  branch: main
media_folder: content/images
public_folder: /assets
# collections:
#   - name: "pages"
#     label: "Pages"
#     label_singular: "Page" # Used in the UI, ie: "New Post"
#     folder: "content/blog"
#     create: true
#     fields:
#       - { label: "Title", name: "title", widget: "string"}
#       - { label: "Publish Date", name: "date", widget: "datetime" }
#       - { label: "Subtitle", name: "subtitle", widget: "string"}
#       - { label: "Cover", name: "cover", widget: "image"}
#       - { label: "Tags", name: "tags", widget: "string" }
#       - { label: "Body", name: "body", widget: "markdown"}
collections:
  - name: homepage
    label: Homepage
    files:
      - label: Homepage
        name: homepage
        file: content/homepage/homepage.json
        fields:
          - label: Introduction
            name: introduction
            widget: object
            fields:
              - {label: Description, name: description, widget: markdown}
              - {label: Newsletter title, name: newsletterTitle, widget: string}
              - {label: Newsletter button text, name: newsletterButton, widget: string}
          - label: Upcoming
            name: upcoming
            widget: object
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Description, name: description, widget: markdown}
            - {label: Video Id, name: video_id, widget: string}
            - label: Links
              name: links
              widget: list
              fields:
                - {label: Name, name: name, widget: string}
                - {label: Url, name: url, widget: string}
                - {label: New window, name: new_window, widget: boolean}
    

